server:
  port: 8008
  servlet:
    context-path: /platform
    session:
      timeout: 7200

multipart:
  maxFileSize: 10Mb
  maxRequestSize: 100Mb

logging:
  level.org.apache.coyote.http11.Http11InputBuffer: trace
  level.cn.sambo: debug
  level.org.activiti.rest: debug
  level.org.hibernate: trace

spring:
  datasource:
    #driver-class-name: com.mysql.jdbc.Driver
    #url: jdbc:mysql://rm-m5eb94r32143ysme9so.mysql.rds.aliyuncs.com:3306/sambo_difference?characterEncoding=UTF-8
    #username: root
    #password: Nttdata123
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mydb?characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: root
  data:
    jpa:
      repositories:
        enabled: true
  jpa:
    generate-ddl: true
    open-in-view: true
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect

  # activiti default configuration
    activiti:
      database-schema-update: true
      check-process-definitions: false
  #    process-definition-location-prefix: classpath:/processes/
  #    process-definition-location-suffixes:
  #      - **.bpmn
  #      - **.bpmn20.xml
      history-level: full

  resources:
    static-locations: classpath:META-INF/resources,classpath:resources/static

  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

file:
  urlPrefix: http://localhost:8008/platform/files/
  store:
      path: c:/temp

pdf:
  urlPrefix: http://localhost:8008/platform/device/
  store:
      path: c:/temp
